name: Deploy to Firebase on Push to Main

on:
  push:
    branches:
      - main
      - 68-fix-so-github-actions-is-included-with-firebase-deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install # Installera alla beroenden

      - name: Build the project
        run: npm run build # Bygg projektet innan deployment

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }} # AnvÃ¤nd service account
        run: |
          echo ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }} > /tmp/google-credentials.json
          export GOOGLE_APPLICATION_CREDENTIALS="/tmp/google-credentials.json"
          firebase deploy --project netflix-dupe-942ea
